In [1]:
import polars as pl

In [2]:
(reverse := 
 pl.read_csv("./data/ReverseCodingItems.csv")
)

shape: (44, 5)
┌─────────────────────────────┬───────────┬──────────────────┬───────────────────────┬─────────────┐
│ Question                    ┆ Construct ┆ Question # on    ┆ Needs Reverse Coding? ┆ Column Name │
│ ---                         ┆ ---       ┆ Qualtrics Survey ┆ ---                   ┆ ---         │
│ str                         ┆ i64       ┆ ---              ┆ str                   ┆ str         │
│                             ┆           ┆ i64              ┆                       ┆             │
╞═════════════════════════════╪═══════════╪══════════════════╪═══════════════════════╪═════════════╡
│ In the future, I plan to    ┆ 1         ┆ 1                ┆ No                    ┆ F1          │
│ parti…                      ┆           ┆                  ┆                       ┆             │
│ Individuals are responsible ┆ 5         ┆ 2                ┆ Yes                   ┆ F5          │
│ fo…                         ┆           ┆                  ┆                       ┆             │
│ When tryng to understand    ┆ 2         ┆ 3                ┆ No                    ┆ F2          │
│ the p…                      ┆           ┆                  ┆                       ┆             │
│ I plan to become involved   ┆ 1         ┆ 4                ┆ No                    ┆ F1.1        │
│ in m…                       ┆           ┆                  ┆                       ┆             │
│ I can communicate well with ┆ 2         ┆ 5                ┆ No                    ┆ F2.1        │
│ ot…                         ┆           ┆                  ┆                       ┆             │
│ …                           ┆ …         ┆ …                ┆ …                     ┆ …           │
│ I prefer the company of     ┆ 6         ┆ 40               ┆ Yes                   ┆ F6.4        │
│ people…                     ┆           ┆                  ┆                       ┆             │
│ I have the ability to lead  ┆ 4         ┆ 41               ┆ No                    ┆ F4.4        │
│ a g…                        ┆           ┆                  ┆                       ┆             │
│ It is important to me that  ┆ 5         ┆ 42               ┆ No                    ┆ F5.7        │
│ equ…                        ┆           ┆                  ┆                       ┆             │
│ I plan to be involved in    ┆ 3         ┆ 43               ┆ No                    ┆ F3.5        │
│ the p…                      ┆           ┆                  ┆                       ┆             │
│ I can successfully resolve  ┆ 2         ┆ 44               ┆ No                    ┆ F2.11       │
│ con…                        ┆           ┆                  ┆                       ┆             │
└─────────────────────────────┴───────────┴──────────────────┴───────────────────────┴─────────────┘

In [27]:
rename_dict = {
    col_name: f"{col_name}_{'rev' if coding == 'Yes' else 'reg'}"
    for col_name, coding in zip(reverse['Column Name'], reverse['Needs Reverse Coding?'])
}
rename_dict

{'F1': 'F1_reg',
 'F5': 'F5_rev',
 'F2': 'F2_reg',
 'F1.1': 'F1.1_reg',
 'F2.1': 'F2.1_reg',
 'F6': 'F6_rev',
 'F4': 'F4_reg',
 'F3': 'F3_reg',
 'F5.1': 'F5.1_reg',
 'F1.2': 'F1.2_reg',
 'F2.2': 'F2.2_reg',
 'F6.1': 'F6.1_reg',
 'F2.3': 'F2.3_reg',
 'F4.1': 'F4.1_rev',
 'F2.4': 'F2.4_reg',
 'F5.2': 'F5.2_rev',
 'F2.5': 'F2.5_reg',
 'F6.2': 'F6.2_reg',
 'F1.3': 'F1.3_reg',
 'F2.6': 'F2.6_reg',
 'F5.3': 'F5.3_reg',
 'F4.2': 'F4.2_reg',
 'F2.7': 'F2.7_reg',
 'F3.1': 'F3.1_reg',
 'F2.8': 'F2.8_reg',
 'F5.4': 'F5.4_reg',
 'F3.2': 'F3.2_reg',
 'F1.4': 'F1.4_reg',
 'F3.3': 'F3.3_reg',
 'F1.5': 'F1.5_reg',
 'F5.5': 'F5.5_rev',
 'F6.3': 'F6.3_rev',
 'F1.6': 'F1.6_reg',
 'F5.6': 'F5.6_rev',
 'F2.9': 'F2.9_reg',
 'F3.4': 'F3.4_reg',
 'F4.3': 'F4.3_rev',
 'F2.10': 'F2.10_reg',
 'F1.7': 'F1.7_reg',
 'F6.4': 'F6.4_rev',
 'F4.4': 'F4.4_reg',
 'F5.7': 'F5.7_reg',
 'F3.5': 'F3.5_reg',
 'F2.11': 'F2.11_reg'}

In [28]:
(health := 
 pl.read_csv("./data/health_survey.csv")
)
health = health.rename(rename_dict)
health

shape: (264, 45)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ID  ┆ F1_reg     ┆ F5_rev     ┆ F2_reg     ┆ … ┆ F4.4_reg   ┆ F5.7_reg   ┆ F3.5_reg  ┆ F2.11_reg │
│ --- ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64 ┆ str        ┆ str        ┆ str        ┆   ┆ str        ┆ str        ┆ str       ┆ str       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1   ┆ Somewhat   ┆ Somewhat   ┆ Somewhat   ┆ … ┆ Somewhat   ┆ Somewhat   ┆ Somewhat  ┆ Somewhat  │
│     ┆ Agree      ┆ Disagree   ┆ Agree      ┆   ┆ Agree      ┆ Agree      ┆ Agree     ┆ Agree     │
│ 2   ┆ Somewhat   ┆ Somewhat   ┆ Somewhat   ┆ … ┆ Neither    ┆ Somewhat   ┆ Neither   ┆ Somewhat  │
│     ┆ Agree      ┆ Disagree   ┆ Agree      ┆   ┆ Agree nor  ┆ Agree      ┆ Agree nor ┆ Agree     │
│     ┆            ┆            ┆            ┆   ┆ Disagree   ┆            ┆ Disagree  ┆           │
│ 3   ┆ Strongly   ┆ Neither    ┆ Somewhat   ┆ … ┆ Somewhat   ┆ Strongly   ┆ Strongly  ┆ Somewhat  │
│     ┆ Agree      ┆ Agree nor  ┆ Agree      ┆   ┆ Agree      ┆ Agree      ┆ Disagree  ┆ Agree     │
│     ┆            ┆ Disagree   ┆            ┆   ┆            ┆            ┆           ┆           │
│ 4   ┆ Somewhat   ┆ Somewhat   ┆ Strongly   ┆ … ┆ Neither    ┆ Somewhat   ┆ Somewhat  ┆ Somewhat  │
│     ┆ Agree      ┆ Agree      ┆ Agree      ┆   ┆ Agree nor  ┆ Agree      ┆ Disagree  ┆ Agree     │
│     ┆            ┆            ┆            ┆   ┆ Disagree   ┆            ┆           ┆           │
│ 5   ┆ Strongly   ┆ Strongly   ┆ Neither    ┆ … ┆ Somewhat   ┆ Strongly   ┆ Somewhat  ┆ Somewhat  │
│     ┆ Agree      ┆ Disagree   ┆ Agree nor  ┆   ┆ Agree      ┆ Agree      ┆ Disagree  ┆ Agree     │
│     ┆            ┆            ┆ Disagree   ┆   ┆            ┆            ┆           ┆           │
│ …   ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 260 ┆ Somewhat   ┆ Somewhat   ┆ Somewhat   ┆ … ┆ Somewhat   ┆ Somewhat   ┆ Somewhat  ┆ Neither   │
│     ┆ Agree      ┆ Disagree   ┆ Agree      ┆   ┆ Agree      ┆ Agree      ┆ Agree     ┆ Agree nor │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆           ┆ Disagree  │
│ 261 ┆ Somewhat   ┆ Somewhat   ┆ Strongly   ┆ … ┆ Somewhat   ┆ Somewhat   ┆ Somewhat  ┆ Somewhat  │
│     ┆ Agree      ┆ Agree      ┆ Agree      ┆   ┆ Agree      ┆ Agree      ┆ Agree     ┆ Agree     │
│ 262 ┆ Somewhat   ┆ Neither    ┆ Somewhat   ┆ … ┆ Strongly   ┆ Neither    ┆ Neither   ┆ Somewhat  │
│     ┆ Agree      ┆ Agree nor  ┆ Agree      ┆   ┆ Agree      ┆ Agree nor  ┆ Agree nor ┆ Agree     │
│     ┆            ┆ Disagree   ┆            ┆   ┆            ┆ Disagree   ┆ Disagree  ┆           │
│ 263 ┆ Strongly   ┆ Somewhat   ┆ Strongly   ┆ … ┆ Somewhat   ┆ Strongly   ┆ Somewhat  ┆ Somewhat  │
│     ┆ Agree      ┆ Disagree   ┆ Agree      ┆   ┆ Agree      ┆ Agree      ┆ Disagree  ┆ Agree     │
│ 264 ┆ Somewhat   ┆ Strongly   ┆ Strongly   ┆ … ┆ Somewhat   ┆ Strongly   ┆ Strongly  ┆ Somewhat  │
│     ┆ Agree      ┆ Disagree   ┆ Agree      ┆   ┆ Agree      ┆ Agree      ┆ Disagree  ┆ Agree     │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [34]:
health_recode = {
       "Strongly Agree": 5,
       "Somewhat Agree": 4,
        "Neutral": 3,
        "Somewhat Disagree": 2,
        "Strongly Disagree": 1,
        "Neither Agree nor Disagree": 3
        
}

health_numeric = health.with_columns(
        pl.col(pl.Utf8).replace(health_recode) 
)

health_numeric.head()

shape: (5, 45)
┌─────┬────────┬────────┬────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ ID  ┆ F1_reg ┆ F5_rev ┆ F2_reg ┆ … ┆ F4.4_reg ┆ F5.7_reg ┆ F3.5_reg ┆ F2.11_reg │
│ --- ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ i64 ┆ str    ┆ str    ┆ str    ┆   ┆ str      ┆ str      ┆ str      ┆ str       │
╞═════╪════════╪════════╪════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 1   ┆ 4      ┆ 2      ┆ 4      ┆ … ┆ 4        ┆ 4        ┆ 4        ┆ 4         │
│ 2   ┆ 4      ┆ 2      ┆ 4      ┆ … ┆ 3        ┆ 4        ┆ 3        ┆ 4         │
│ 3   ┆ 5      ┆ 3      ┆ 4      ┆ … ┆ 4        ┆ 5        ┆ 1        ┆ 4         │
│ 4   ┆ 4      ┆ 4      ┆ 5      ┆ … ┆ 3        ┆ 4        ┆ 2        ┆ 4         │
│ 5   ┆ 5      ┆ 1      ┆ 3      ┆ … ┆ 4        ┆ 5        ┆ 2        ┆ 4         │
└─────┴────────┴────────┴────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [35]:
health_recoded = health_numeric.with_columns(
    [
        (6 - pl.col(c)).alias(c.removesuffix('_rev'))
        for c in health_numeric.select(pl.col(r".*_rev$")).columns
    ]
)

ColumnNotFoundError: unable to find column ".*_rev$"; valid columns: ["ID", "F1_reg", "F5_rev", "F2_reg", "F1.1_reg", "F2.1_reg", "F6_rev", "F4_reg", "F3_reg", "F5.1_reg", "F1.2_reg", "F2.2_reg", "F6.1_reg", "F2.3_reg", "F4.1_rev", "F2.4_reg", "F5.2_rev", "F2.5_reg", "F6.2_reg", "F1.3_reg", "F2.6_reg", "F5.3_reg", "F4.2_reg", "F2.7_reg", "F3.1_reg", "F2.8_reg", "F5.4_reg", "F3.2_reg", "F1.4_reg", "F3.3_reg", "F1.5_reg", "F5.5_rev", "F6.3_rev", "F1.6_reg", "F5.6_rev", "F2.9_reg", "F3.4_reg", "F4.3_rev", "F2.10_reg", "F1.7_reg", "F6.4_rev", "F4.4_reg", "F5.7_reg", "F3.5_reg", "F2.11_reg"]

In [33]:
question_pre = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6']
health_agg = health_recoded.select(
    [
        pl.reduce(
            lambda a, b: a + b,
            exprs = [pl.col(c).fill_null(0) for c in health_recoded.select(pl.col(f"^{p}_.*$")).columns]
        ).alias(f"{p}_total")
        for p in question_pre
    ]
)

print(health_agg.head())

NameError: name 'health_recoded' is not defined